# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true

# Enable AndroidX and modern R class behavior (Required for AndroidX dependencies and AGP 8+)
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official
